id: A2D0C4722
title: Prayer to Ārya Tārā
type: translation
pechas:
- IB24EE9B1
- I927E277E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:43:06.133576
  last_modified_at: 2023-01-04 11:43:06.133585
  collections:
  - Dodrupchen Jigme Tenpe Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  IB24EE9B1/2EA3: 07C7
  I927E277E/9E53: 07C7
